# pull official base image
FROM node:12.16.2-alpine 

RUN mkdir -p /usr/src/app
# set working directory
WORKDIR /usr/src/app

# install app dependencies
COPY package.json /usr/src/app
RUN npm install

# add app
COPY . /usr/src/app

EXPOSE 5002

# start app
CMD ["node", "index.js"]
